version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: sqlserver_local
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=R#256123904
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: always

volumes:
  sqlserver_data:
